language: node_js
node_js:
  - "6"
  - "7"
  - "stable"

sudo: required

services:
    - docker

before_script:
  - docker-compose -f docker-compose.dev.yml up -d mongo-test
  - npm run build

script:
  - npm run lint
  - npm run test

after_script:
  - npm run update-coveralls