language: node_js
node_js:
  - "4"
  - "5"
  - "stable"

sudo: required

services:
    - docker

before_script:
  - docker-compose -f docker-compose.dev.yml up mongo-test
  - npm run build

script:
  - npm run lint
  - npm run test

after_script:
  - npm run update-coveralls