version: '2'
services:
  postgres:
    restart: always
    image: postgres:9.4
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: weedo
      POSTGRES_PASSWORD: weedo-pw
  postgres-test:
    restart: always
    image: postgres:9.4
    ports:
      - "5556:5432"
    volumes:
      - ./data/postgres-test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: weedo-test
      POSTGRES_PASSWORD: weedo-test-pw